require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BugreportsController do

  # This should return the minimal set of attributes required to create a valid
  # Bugreport. As you add validations to Bugreport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "subject" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BugreportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bugreports as @bugreports" do
      bugreport = Bugreport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bugreports).should eq([bugreport])
    end
  end

  describe "GET show" do
    it "assigns the requested bugreport as @bugreport" do
      bugreport = Bugreport.create! valid_attributes
      get :show, {:id => bugreport.to_param}, valid_session
      assigns(:bugreport).should eq(bugreport)
    end
  end

  describe "GET new" do
    it "assigns a new bugreport as @bugreport" do
      get :new, {}, valid_session
      assigns(:bugreport).should be_a_new(Bugreport)
    end
  end

  describe "GET edit" do
    it "assigns the requested bugreport as @bugreport" do
      bugreport = Bugreport.create! valid_attributes
      get :edit, {:id => bugreport.to_param}, valid_session
      assigns(:bugreport).should eq(bugreport)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bugreport" do
        expect {
          post :create, {:bugreport => valid_attributes}, valid_session
        }.to change(Bugreport, :count).by(1)
      end

      it "assigns a newly created bugreport as @bugreport" do
        post :create, {:bugreport => valid_attributes}, valid_session
        assigns(:bugreport).should be_a(Bugreport)
        assigns(:bugreport).should be_persisted
      end

      it "redirects to the created bugreport" do
        post :create, {:bugreport => valid_attributes}, valid_session
        response.should redirect_to(Bugreport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bugreport as @bugreport" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bugreport.any_instance.stub(:save).and_return(false)
        post :create, {:bugreport => { "subject" => "invalid value" }}, valid_session
        assigns(:bugreport).should be_a_new(Bugreport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bugreport.any_instance.stub(:save).and_return(false)
        post :create, {:bugreport => { "subject" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bugreport" do
        bugreport = Bugreport.create! valid_attributes
        # Assuming there are no other bugreports in the database, this
        # specifies that the Bugreport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bugreport.any_instance.should_receive(:update).with({ "subject" => "MyString" })
        put :update, {:id => bugreport.to_param, :bugreport => { "subject" => "MyString" }}, valid_session
      end

      it "assigns the requested bugreport as @bugreport" do
        bugreport = Bugreport.create! valid_attributes
        put :update, {:id => bugreport.to_param, :bugreport => valid_attributes}, valid_session
        assigns(:bugreport).should eq(bugreport)
      end

      it "redirects to the bugreport" do
        bugreport = Bugreport.create! valid_attributes
        put :update, {:id => bugreport.to_param, :bugreport => valid_attributes}, valid_session
        response.should redirect_to(bugreport)
      end
    end

    describe "with invalid params" do
      it "assigns the bugreport as @bugreport" do
        bugreport = Bugreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bugreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => bugreport.to_param, :bugreport => { "subject" => "invalid value" }}, valid_session
        assigns(:bugreport).should eq(bugreport)
      end

      it "re-renders the 'edit' template" do
        bugreport = Bugreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bugreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => bugreport.to_param, :bugreport => { "subject" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bugreport" do
      bugreport = Bugreport.create! valid_attributes
      expect {
        delete :destroy, {:id => bugreport.to_param}, valid_session
      }.to change(Bugreport, :count).by(-1)
    end

    it "redirects to the bugreports list" do
      bugreport = Bugreport.create! valid_attributes
      delete :destroy, {:id => bugreport.to_param}, valid_session
      response.should redirect_to(bugreports_url)
    end
  end

end
