require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BusinessprocessesController do

  # This should return the minimal set of attributes required to create a valid
  # Businessprocess. As you add validations to Businessprocess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "customerid" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BusinessprocessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all businessprocesses as @businessprocesses" do
      businessprocess = Businessprocess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:businessprocesses).should eq([businessprocess])
    end
  end

  describe "GET show" do
    it "assigns the requested businessprocess as @businessprocess" do
      businessprocess = Businessprocess.create! valid_attributes
      get :show, {:id => businessprocess.to_param}, valid_session
      assigns(:businessprocess).should eq(businessprocess)
    end
  end

  describe "GET new" do
    it "assigns a new businessprocess as @businessprocess" do
      get :new, {}, valid_session
      assigns(:businessprocess).should be_a_new(Businessprocess)
    end
  end

  describe "GET edit" do
    it "assigns the requested businessprocess as @businessprocess" do
      businessprocess = Businessprocess.create! valid_attributes
      get :edit, {:id => businessprocess.to_param}, valid_session
      assigns(:businessprocess).should eq(businessprocess)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Businessprocess" do
        expect {
          post :create, {:businessprocess => valid_attributes}, valid_session
        }.to change(Businessprocess, :count).by(1)
      end

      it "assigns a newly created businessprocess as @businessprocess" do
        post :create, {:businessprocess => valid_attributes}, valid_session
        assigns(:businessprocess).should be_a(Businessprocess)
        assigns(:businessprocess).should be_persisted
      end

      it "redirects to the created businessprocess" do
        post :create, {:businessprocess => valid_attributes}, valid_session
        response.should redirect_to(Businessprocess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved businessprocess as @businessprocess" do
        # Trigger the behavior that occurs when invalid params are submitted
        Businessprocess.any_instance.stub(:save).and_return(false)
        post :create, {:businessprocess => { "customerid" => "invalid value" }}, valid_session
        assigns(:businessprocess).should be_a_new(Businessprocess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Businessprocess.any_instance.stub(:save).and_return(false)
        post :create, {:businessprocess => { "customerid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested businessprocess" do
        businessprocess = Businessprocess.create! valid_attributes
        # Assuming there are no other businessprocesses in the database, this
        # specifies that the Businessprocess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Businessprocess.any_instance.should_receive(:update).with({ "customerid" => "1" })
        put :update, {:id => businessprocess.to_param, :businessprocess => { "customerid" => "1" }}, valid_session
      end

      it "assigns the requested businessprocess as @businessprocess" do
        businessprocess = Businessprocess.create! valid_attributes
        put :update, {:id => businessprocess.to_param, :businessprocess => valid_attributes}, valid_session
        assigns(:businessprocess).should eq(businessprocess)
      end

      it "redirects to the businessprocess" do
        businessprocess = Businessprocess.create! valid_attributes
        put :update, {:id => businessprocess.to_param, :businessprocess => valid_attributes}, valid_session
        response.should redirect_to(businessprocess)
      end
    end

    describe "with invalid params" do
      it "assigns the businessprocess as @businessprocess" do
        businessprocess = Businessprocess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Businessprocess.any_instance.stub(:save).and_return(false)
        put :update, {:id => businessprocess.to_param, :businessprocess => { "customerid" => "invalid value" }}, valid_session
        assigns(:businessprocess).should eq(businessprocess)
      end

      it "re-renders the 'edit' template" do
        businessprocess = Businessprocess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Businessprocess.any_instance.stub(:save).and_return(false)
        put :update, {:id => businessprocess.to_param, :businessprocess => { "customerid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested businessprocess" do
      businessprocess = Businessprocess.create! valid_attributes
      expect {
        delete :destroy, {:id => businessprocess.to_param}, valid_session
      }.to change(Businessprocess, :count).by(-1)
    end

    it "redirects to the businessprocesses list" do
      businessprocess = Businessprocess.create! valid_attributes
      delete :destroy, {:id => businessprocess.to_param}, valid_session
      response.should redirect_to(businessprocesses_url)
    end
  end

end
